version: "3.9"
services:
  hisquiz-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: hisquiz-app
    ports:
      - "3000:3000"
    volumes:
    - ./:/app
    tty: true